package org.mose.boot.system.repository.mysql;

import org.mose.boot.common.dao.stream.AbstractStreamRepository;
import org.mose.boot.system.modal.Authority;
import org.mose.boot.system.modal.User;
import org.mose.boot.system.repository.IAuthorityRepository;
import org.mose.boot.util.code.ReturnCodeUtil;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Description:
 *
 * @Author: 靳磊
 * @Date: 2017/8/14:22
 */
@Component
public class AuthorityMysqlRepository extends AbstractStreamRepository<Authority, Integer> implements IAuthorityRepository {
    @Override
    public Authority queryOne(int id) {
        String sql = "select id, name, description from t_system_authority t where id=?";
        return query().sql(sql).parameters(id).queryOne();
    }

    @Override
    public boolean queryExistByName(String name) {
        String sql = "select count(id) from t_system_authority t where t.name=?";
        int count = query().sql(sql).parameters(name).queryCount();
        return count > 0;
    }

    @Override
    public List<Authority> queryAll() {
        String sql = "select id, name, description from t_system_authority t order by t.name";
        return query().sql(sql).queryMany();
    }

    @Override
    public List<Authority> queryMany(int pageNumber, int pageRowCount) {
        String sql = "select id, name, description from t_system_authority t order by t.name";
        return query().sql(sql).paging(pageNumber, pageRowCount).queryMany();
    }


    @Override
    public int queryCount() {
        String sql = "select count(id) from t_system_authority";
        return query().sql(sql).queryCount();
    }

    @Override
    public List<Authority> queryAllByRoleId(int roleId) {
        String sql = "select a.id, a.name, a.description from t_system_authority a left outer join t_system_role_authority ra on ra.authority_id=a.id where ra.role_id=? order by a.name";
        return query().sql(sql).parameters(roleId).queryMany();
    }

    @Override
    public List<Authority> queryAllByUserId(int userId) {
        StringBuilder sql = new StringBuilder();
        sql.append("select nra.id, nra.name, nra.description from");
        sql.append(" (select ra.role_id, a.id, a.name, a.description from t_system_authority a left outer join t_system_role_authority ra on ra.authority_id=a.id) nra");
        sql.append(" left outer join t_system_user_role ur on nra.role_id=ur.role_id");
        sql.append(" where ur.user_id=? order by nra.name");
        return query().sql(sql.substring(0)).parameters(userId).queryMany();
    }


    @Override
    public int insertOne(Authority authority) {
        //不允许写入名称一样的权限
        boolean exist = queryExistByName(authority.getName());
        if (exist) {
            return ReturnCodeUtil.FAIL__INSERT_EXIST;
        }

        StringBuffer sql = new StringBuffer();
        sql.append("insert into t_system_authority(name, description)");
        sql.append(" values(:name, :description)");
        Number id = insert().sql(sql.substring(0)).entity(authority).idColumnName("id").insertOneForAutoGeneratedId();
        if (id == null) {
            return ReturnCodeUtil.FAIL__INSERT;
        } else {
            authority.setId(id.intValue());
            return ReturnCodeUtil.SUCCESS__INSERT;
        }
    }

    @Override
    public int updateOne(Authority authority) {
        StringBuffer sql = new StringBuffer();
        sql.append("update t_system_authority set description=:description");
        sql.append(" where id=:id");
        int rowCount = update().sql(sql.substring(0)).parameterBean(authority).updateAny();
        if (rowCount > 0) {
            return ReturnCodeUtil.SUCCESS__UPDATE;
        } else {
            return ReturnCodeUtil.FAIL__UPDATE_NONE;
        }
    }

    @Override
    public int deleteOne(Authority authority) {
        return deleteOne(authority.getId());
    }

    @Override
    public int deleteOne(int id) {
        String sql = "delete from t_system_authority where id=?";
        delete().sql(sql).parameters(id).deleteAny();
        return ReturnCodeUtil.SUCCESS__DELETE;
    }
}
