package org.mose.boot.system.repository.mysql;

import org.mose.boot.common.dao.stream.AbstractStreamRepository;
import org.mose.boot.system.modal.Role;
import org.mose.boot.system.repository.IRoleAuthorityRepository;
import org.mose.boot.system.repository.IRoleRepository;
import org.mose.boot.util.code.ReturnCodeUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Description:
 *
 * @Author: 靳磊
 * @Date: 2017/8/14:22
 */
@Component
public class RoleMysqlRepository extends AbstractStreamRepository<Integer, Role> implements IRoleRepository {
    @Autowired
    private IRoleAuthorityRepository roleAuthorityRepository;

    @Override
    public Role queryOne(int id) {
        String sql = "select id, name from t_system_role t where id=?";
        return query().sql(sql).parameters(id).queryOne();
    }

    @Override
    public List<Role> queryAll() {
        String sql = "select id, name from t_system_role t";
        return query().sql(sql).queryMany();
    }

    @Override
    public List<Role> queryAllByUserId(int userId) {
        String sql = "select r.id, r.name from t_system_role r left outer join t_system_user_role ur on ur.role_id=r.id where ur.user_id=?";
        return query().sql(sql).parameters(userId).queryMany();
    }

    @Override
    public int insertOne(Role role) {
        StringBuffer sql = new StringBuffer();
        sql.append("insert into t_system_role(name)");
        sql.append(" values(:name)");
        Number id = insert().sql(sql.substring(0)).entity(role).idColumnName("id").insertOneForAutoGeneratedId();
        if (id == null) {
            return ReturnCodeUtil.FAIL__INSERT;
        } else {
            role.setId(id.intValue());
            return ReturnCodeUtil.SUCCESS__INSERT;
        }
    }

    @Override
    public int updateOne(Role role) {
        StringBuffer sql = new StringBuffer();
        sql.append("update t_system_role set name=:name");
        sql.append(" where id=:id");
        int rowCount = update().sql(sql.substring(0)).parameterBean(role).updateAny();
        if (rowCount > 0) {
            return ReturnCodeUtil.SUCCESS__UPDATE;
        } else {
            return ReturnCodeUtil.FAIL__UPDATE_NONE;
        }
    }

    @Override
    public int deleteOne(Role role) {
        return deleteOne(role.getId());
    }

    @Override
    public int deleteOne(int id) {
        int returnCode = roleAuthorityRepository.deleteAllByRoleId(id);
        if (ReturnCodeUtil.isFail(returnCode)) {
            return returnCode;
        }

        String sql = "delete from t_system_role where id=?";
        delete().sql(sql).parameters(id).deleteAny();
        return ReturnCodeUtil.SUCCESS__DELETE;
    }
}
