package org.mose.springboot.system.dao;

import org.mose.springboot.dao.stream.AbstractStreamRepository;
import org.mose.springboot.system.modal.Module;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Description:
 *
 * @Author: 靳磊
 * @Date: 2017/8/14:22
 */
@Profile("mysql")
@Component
public class ModuleMysqlRepository extends AbstractStreamRepository<Module, Integer> implements IModuleRepository {
    @Override
    public Module queryOne(int id) {
        String sql = "select id, name, description, parent_id, scenario_id, icon, display_order from T_MODULE where id=?";
        return query().sql(sql).parameters(id).queryOne();
    }

    @Override
    public List<Module> queryAll() {
        String sql = "select id, name ,description, parent_id, scenario_id, icon, display_order from T_MODULE";
        return query().sql(sql).queryMany();
    }

    @Override
    public Integer insertOne(Module module) {
        StringBuffer sql = new StringBuffer();
        sql.append("insert into T_MODULE(name, description, parent_id, scenario_id, icon, display_order)");
        sql.append(" values(:name, :description, :parentId, :scenarioId, :icon, :displayOrder)");
        Number id = insert().sql(sql.substring(0)).entity(module).idColumnName(
                "id").insertOneForAutoGeneratedId();
        return id == null ? null : id.intValue();
    }

    @Override
    public int updateOne(Module module) {
        StringBuffer sql = new StringBuffer();
        sql.append("update T_MODULE set name=:name, description=:description, parent_id=:parentId, scenario_id=:scenarioId, icon=:icon, display_order=:displayOrder");
        sql.append(" where id=:id");
        return update().sql(sql.substring(0)).parameterBean(module).updateAny();
    }

    @Override
    public int deleteOne(Module module) {
        String sql = "delete from T_MODULE where id=:id";
        return delete().sql(sql).parameterBean(module).deleteAny();
    }
}
