package org.mose.springboot.system.dao;

import org.mose.springboot.dao.stream.AbstractStreamRepository;
import org.mose.springboot.system.modal.Scenario;
import org.mose.springboot.util.code.ReturnCodeUtil;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Description:
 *
 * @Author: 靳磊
 * @Date: 2017/8/14:22
 */
@Component
public class ScenarioMysqlRepository extends AbstractStreamRepository<Scenario, Integer> implements IScenarioRepository {
    @Override
    public Scenario queryOne(int id) {
        String sql = "select id, name, description, parent_id, url, url_target, icon, display_order, (select name from t_scenario where id=t.parent_id) parent_name from T_SCENARIO t where id=?";
        return query().sql(sql).parameters(id).queryOne();
    }

    @Override
    public List<Scenario> queryAll() {
        String sql = "select id, name ,description, parent_id, url, url_target, icon, display_order from T_SCENARIO";
        return query().sql(sql).queryMany();
    }

    @Override
    public int insertOne(Scenario scenario) {
        StringBuffer sql = new StringBuffer();
        sql.append("insert into T_SCENARIO(name, description, parent_id, url, url_target, icon, display_order)");
        sql.append(" values(:name, :description, :parentId, :url, :urlTarget, :icon, :displayOrder)");
        Number id = insert().sql(sql.substring(0)).entity(scenario).idColumnName(
                "id").insertOneForAutoGeneratedId();
        if (id == null) {
            return ReturnCodeUtil.FAIL__SAVE;
        } else {
            scenario.setId(id.intValue());
            return ReturnCodeUtil.SUCCESS__SAVE;
        }
    }

    @Override
    public int updateOne(Scenario scenario) {
        StringBuffer sql = new StringBuffer();
        sql.append("update T_SCENARIO set name=:name, description=:description, parent_id=:parentId, url=:url, url_target=:urlTarget, icon=:icon, display_order=:displayOrder");
        sql.append(" where id=:id");
        int rowCount = update().sql(sql.substring(0)).parameterBean(scenario).updateAny();
        if (rowCount > 0) {
            return ReturnCodeUtil.SUCCESS__UPDATE;
        } else {
            return ReturnCodeUtil.FAIL__UPDATE_NULL;
        }
    }

    @Override
    public int deleteOne(Scenario scenario) {
        return deleteOne(scenario.getId());
    }

    @Override
    public int deleteOne(int id) {
        int childrenCount = queryChildrenCount(id);
        if (childrenCount > 0) {
            return ReturnCodeUtil.FAIL__DELETE_HAVE_CHILDREN;
        } else {
            String sql = "delete from T_SCENARIO where id=?";
            return delete().sql(sql).parameters(id).deleteAny();
        }
    }


    @Override
    public int queryChildrenCount(int id) {
        String sql = "select count(id) from T_SCENARIO where parent_id=?";
        return query().sql(sql).parameters(id).queryCount();
    }
}
